runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/.*
  script: main.app

libraries:
- name: flask
  version: "0.12"

env_variables:
    PROJECT_ID: 'your-project-id-goes here'
    PUBSUB_TOPIC: 'your-pubsub-notification-topic-full-name-goes-here'
    PUBSUB_VERIFICATION_TOKEN: 'random-value-you-configured-push-topic-with'
